-- Badges de valeurs : table + jointures brand_badges / showroom_badges + seed

-- 1) Table badges
CREATE TABLE IF NOT EXISTS public.badges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  label text NOT NULL,
  icon text,
  sort_order smallint DEFAULT 0
);

COMMENT ON TABLE public.badges IS 'Badges de valeurs (Made in France, Bio, etc.) affichés sur les fiches marques et boutiques.';

-- 2) Jointure marques <-> badges (max 5 par marque côté UI)
CREATE TABLE IF NOT EXISTS public.brand_badges (
  brand_id bigint NOT NULL REFERENCES public.brands(id) ON DELETE CASCADE,
  badge_id bigint NOT NULL REFERENCES public.badges(id) ON DELETE CASCADE,
  PRIMARY KEY (brand_id, badge_id)
);

CREATE INDEX IF NOT EXISTS brand_badges_badge_id_idx ON public.brand_badges(badge_id);

-- 3) Jointure showrooms (boutiques) <-> badges (max 5 par boutique côté UI)
CREATE TABLE IF NOT EXISTS public.showroom_badges (
  showroom_id bigint NOT NULL REFERENCES public.showrooms(id) ON DELETE CASCADE,
  badge_id bigint NOT NULL REFERENCES public.badges(id) ON DELETE CASCADE,
  PRIMARY KEY (showroom_id, badge_id)
);

CREATE INDEX IF NOT EXISTS showroom_badges_badge_id_idx ON public.showroom_badges(badge_id);

-- RLS badges : lecture publique
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "badges_select_all" ON public.badges;
CREATE POLICY "badges_select_all" ON public.badges FOR SELECT USING (true);

-- RLS brand_badges : lecture publique, écriture propriétaire
ALTER TABLE public.brand_badges ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "brand_badges_select_all" ON public.brand_badges;
CREATE POLICY "brand_badges_select_all" ON public.brand_badges FOR SELECT USING (true);
DROP POLICY IF EXISTS "brand_badges_insert_own" ON public.brand_badges;
CREATE POLICY "brand_badges_insert_own" ON public.brand_badges FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.brands b WHERE b.id = brand_id AND b.owner_id = auth.uid()));
DROP POLICY IF EXISTS "brand_badges_delete_own" ON public.brand_badges;
CREATE POLICY "brand_badges_delete_own" ON public.brand_badges FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.brands b WHERE b.id = brand_id AND b.owner_id = auth.uid()));

-- RLS showroom_badges : lecture publique, écriture propriétaire
ALTER TABLE public.showroom_badges ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "showroom_badges_select_all" ON public.showroom_badges;
CREATE POLICY "showroom_badges_select_all" ON public.showroom_badges FOR SELECT USING (true);
DROP POLICY IF EXISTS "showroom_badges_insert_own" ON public.showroom_badges;
CREATE POLICY "showroom_badges_insert_own" ON public.showroom_badges FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM public.showrooms s WHERE s.id = showroom_id AND s.owner_id = auth.uid()));
DROP POLICY IF EXISTS "showroom_badges_delete_own" ON public.showroom_badges;
CREATE POLICY "showroom_badges_delete_own" ON public.showroom_badges FOR DELETE
  USING (EXISTS (SELECT 1 FROM public.showrooms s WHERE s.id = showroom_id AND s.owner_id = auth.uid()));

-- 4) Seed : liste des badges de valeurs
INSERT INTO public.badges (slug, label, icon, sort_order) VALUES
  ('made-in-france', 'Made in France', '🇫🇷', 1),
  ('bio', 'Bio', '🌿', 2),
  ('upcycling', 'Upcycling', '♻️', 3),
  ('artisanal', 'Artisanal', '🖐️', 4),
  ('vegan', 'Vegan', '🌱', 5),
  ('zero-dechet', 'Zéro Déchet', '🗑️', 6),
  ('made-in-europe', 'Made in Europe', '🇪🇺', 7),
  ('kids-friendly', 'Kids Friendly', '👶', 8),
  ('bien-etre', 'Bien-être', '🧘', 9)
ON CONFLICT (slug) DO NOTHING;
