-- Options de rémunération proposées par le showroom (jusqu'à 3)
-- Chaque option : loyer optionnel + % commission optionnel + description (ex. m², type d'espace)

create table public.showroom_commission_options (
  id bigint generated by default as identity not null,
  showroom_id bigint not null,
  sort_order smallint not null,
  rent numeric(12, 2) null,
  rent_period text null default 'month',
  commission_percent numeric(5, 2) null,
  description text null,
  constraint showroom_commission_options_pkey primary key (id),
  constraint showroom_commission_options_showroom_id_fkey foreign key (showroom_id) references public.showrooms (id) on delete cascade,
  constraint showroom_commission_options_showroom_sort_unique unique (showroom_id, sort_order),
  constraint showroom_commission_options_sort_order_check check (sort_order >= 1 and sort_order <= 3),
  constraint showroom_commission_options_rent_check check (rent is null or rent >= 0),
  constraint showroom_commission_options_rent_period_check check (rent_period is null or rent_period in ('week', 'month', 'one_off')),
  constraint showroom_commission_options_commission_check check (
    commission_percent is null or (commission_percent >= 0 and commission_percent <= 100)
  )
) tablespace pg_default;

create index showroom_commission_options_showroom_id_idx on public.showroom_commission_options using btree (showroom_id);

comment on table public.showroom_commission_options is 'Jusqu''à 3 modèles de rémunération par showroom : loyer et/ou % commission + description (m², type d''espace).';

-- RLS : lecture pour tous (marques voient les options sur Découvrir), écriture pour le propriétaire du showroom
alter table public.showroom_commission_options enable row level security;

drop policy if exists "showroom_commission_options_select" on public.showroom_commission_options;
create policy "showroom_commission_options_select" on public.showroom_commission_options
  for select using (true);

drop policy if exists "showroom_commission_options_insert" on public.showroom_commission_options;
create policy "showroom_commission_options_insert" on public.showroom_commission_options
  for insert with check (
    exists (select 1 from public.showrooms s where s.id = showroom_commission_options.showroom_id and s.owner_id = auth.uid())
  );

drop policy if exists "showroom_commission_options_update" on public.showroom_commission_options;
create policy "showroom_commission_options_update" on public.showroom_commission_options
  for update using (
    exists (select 1 from public.showrooms s where s.id = showroom_commission_options.showroom_id and s.owner_id = auth.uid())
  );

drop policy if exists "showroom_commission_options_delete" on public.showroom_commission_options;
create policy "showroom_commission_options_delete" on public.showroom_commission_options
  for delete using (
    exists (select 1 from public.showrooms s where s.id = showroom_commission_options.showroom_id and s.owner_id = auth.uid())
  );

-- Si la table a été créée avant l’ajout de rent_period, exécuter : supabase-showroom-commission-options-rent-period.sql
